name: color_wand
version: 0.0.3
description: A color library which can be used to create, convert, alter, and compare colors to be used in both Flutter and the web.
authors:
  - Tobias Marschall <tobias.marschall@online.de>
homepage: https://github.com/tio-design/color_wand
environment:
  sdk: '>=2.0.0-dev.61.0 <3.0.0'

dependencies:
  meta: ^1.0.0

dev_dependencies:
  test: ^1.0.0